apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - /hyperkube
    - controller-manager
    - --master=<%= properties.apiserver.ip %>:8080
    - 1>>/var/log/kube-controller-manager.log 2>&1
    image: gcr.io/google_containers/hyperkube-amd64:v1.3.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      limits:
        cpu: 200m
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /srv/kubernetes
      name: srvkube
      readOnly: true
    - mountPath: /var/log/kube-controller-manager.log
      name: logfile
      readOnly: true
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  volumes:
  - hostPath:
      path: /var/vcap/store/kubernetes/controller-manager
    name: srvkube
  - hostPath:
      path: /var/log/kube-controller-manager.log
    name: logfile
