apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - /hyperkube
    - scheduler
    - --master=<%= properties.apiserver.ip %>:8080
    - 1>>/var/log/kube-scheduler.log 2>&1
    image: gcr.io/google_containers/hyperkube-amd64:v1.3.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /var/log/kube-scheduler.log
      name: logfile
  dnsPolicy: ClusterFirst
  hostNetwork: true
  nodeName: ${INSTANCE_PREFIX}-master
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  volumes:
  - hostPath:
      path: /var/log/kube-scheduler.log
    name: logfile