meta:
  environment: kubernetes-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: master
    networks:
      - name: kubernetes1
        static_ips: (( static_ips(0) ))

  - name: node
    networks:
      - name: kubernetes1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: kubernetes1
  type: manual
  subnets:
  - cloud_properties: {}
    range: 10.244.0.0/30
    reserved:
      - 10.244.0.1
    static:
      - 10.244.0.2

  - cloud_properties: {}
    name: random
    range: 10.244.0.4/30
    reserved:
      - 10.244.0.5
    static: []

  - cloud_properties: {}
    name: random
    range: 10.244.0.8/30
    reserved:
      - 10.244.0.9
    static: []

  - cloud_properties: {}
    name: random
    range: 10.244.0.12/30
    reserved:
      - 10.244.0.13
    static: []

  - cloud_properties: {}
    name: random
    range: 10.244.0.16/30
    reserved:
      - 10.244.0.17
    static: []

  - cloud_properties: {}
    name: random
    range: 10.244.0.20/30
    reserved:
      - 10.244.0.21
    static: []

  - cloud_properties: {}
    name: random
    range: 10.244.0.24/30
    reserved:
      - 10.244.0.25
    static: []

  - cloud_properties: {}
    name: random
    range: 10.244.0.28/30
    reserved:
      - 10.244.0.29
    static: []

  - cloud_properties: {}
    name: random
    range: 10.244.0.32/30
    reserved:
      - 10.244.0.33
    static: []

  - cloud_properties: {}
    name: random
    range: 10.244.0.36/30
    reserved:
      - 10.244.0.37
    static: []

properties:
  apiserver:
    ip: (( grab jobs.master.networks.kubernetes1.static_ips[0] ))
  etcd:
    machines: (( grab jobs.master.networks.kubernetes1.static_ips ))
    peer_require_ssl: false
    require_ssl: false