meta:
  environment: kubernetes-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: master
    networks:
      - name: kubernetes1
        static_ips: (( static_ips(0) ))

  - name: node
    networks:
      - name: kubernetes1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: kubernetes1
  type: manual
  subnets:
  - range: 10.244.221.0/24
    name: kubernetes1
    gateway: 10.244.221.1
    static:
      - 10.244.221.2 - 10.244.221.60

properties:
  apiserver:
    ip: (( grab jobs.master.networks.kubernetes1.static_ips[0] ))
  etcd:
    machines: (( grab jobs.master.networks.kubernetes1.static_ips ))
    peer_require_ssl: false
    require_ssl: false