meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: master
    templates:
    - name: etcd
      release: etcd
    - name: flannel
      release: docker
    - name: docker
      release: docker
    - name: node
      release: kubernetes
    instances: 1
    persistent_disk: 4096
    resource_pool: small_z1
    networks: (( param "please set just_install_package networks" ))
    properties:
      kubernetes:
        master: true

  - name: node
    templates:
    - name: flannel
      release: docker
    - name: docker
      release: docker
    - name: node
      release: kubernetes
    instances: 3
    persistent_disk: 4096
    resource_pool: small_z1
    networks: (( param "please set just_install_package networks" ))


networks: (( param "please set networks" ))

properties:
  docker:
    flannel: true

